composer.json

This PR adds the conflict note for composer for `"slim/slim": "^3.0"`. My understanding is that `slim/http` targets upcoming Slim 4 and is not supposed to be used with Slim 3. Furthermore installing `slim/http` into Slim 3 project will break the app with the error below.
```
Call to undefined method Slim\\Http\\Request::createFromEnvironment()
```
There also is some confusion with third party code such as [http-interop/http-factory-slim](https://github.com/http-interop/http-factory-slim) which was meant to be used with Slim 3 but currently wrongly includes `slim/http` instead of `slim/slim`. I am also submitting a PR for that project soonish.

Conflict with Slim 3

---

.travis.yml

Asserts library works in PHP7.1.  Adds nightly build as allowable failure.

Minor build process alteration

---

src/Request.php
tests/RequestTest.php

This method was originally used in Slim 3.x to instantiate the Request.
In Slim-Http there's a dedicated FactoryDefault class for that, and `Uri::createFromGlobals(array $globals)` does not even exist anymore.

Remove deprecated factory

---

src/Request.php
tests/RequestTest.php

This should fix slimphp/Slim#2169 by removing strtoupper from request method.

Allow request method to be case sensitive

---

src/Body.php
src/Collection.php
src/CollectionInterface.php
src/Cookies.php
src/CookiesInterface.php
src/Environment.php
src/Headers.php
src/HeadersInterface.php
src/Message.php
src/Request.php
src/RequestBody.php
src/Response.php
src/Stream.php
src/UploadedFile.php
src/Uri.php
tests/BodyTest.php
tests/CollectionTest.php
tests/CookiesTest.php
tests/EnvironmentTest.php
tests/HeadersTest.php
tests/MessageTest.php
tests/Mocks/MessageStub.php
tests/RequestBodyTest.php
tests/RequestTest.php
tests/ResponseTest.php
tests/StreamTest.php
tests/UploadedFilesTest.php
tests/UriTest.php

The links in the license header still points to slim 3, they should point to their own repository.

Fix links in license header to slim-http instead of slim

---

composer.json

As this package provides a http-message-implementation we should add this information in the composer.json.

Add provides http-message-implementation

---

composer.json
src/Uri.php
tests/Integration/BaseTestFactories.php
tests/Integration/ResponseTest.php
tests/Integration/ServerRequestTest.php
tests/Integration/StreamTest.php
tests/Integration/UploadedFileTest.php
tests/Integration/UriTest.php

Added `php-http/psr7-integration-tests` for testing our implementation. Fixed the only failing part right now - Host in Uri must be lowercase as of 
> The value returned MUST be normalized to lowercase, per RFC 3986
closes #31

Psr7 integration tests

---

src/Uri.php
tests/UriTest.php

If the username or password includes an `@` or `:` or other reserved
characters, they need to be encoded.
Fixes #34
Forward ports https://github.com/slimphp/Slim/pull/2327.

Encode user info

---

src/Environment.php
tests/EnvironmentTest.php

Same issue fixed on Slim.  Adds HTTPS default port when environment is created,

Add 443 as SERVER_PORT(default) when request is https

---

src/Uri.php
tests/Integration/UploadedFileTest.php

After php-http/psr7-integration-tests finally added some tests for UploadedFile I checked if we are compatible and found out that our test setup of the UploadedFile was wrong, which ended in errors running PHPUnit.
Now the tests should be running fine.
Edit:
With latest updates Uri integration tests were failing too.

Fixed integration tests for UploadedFile, Uri

---

src/Uri.php

We no longer need to worry about parse_url and rawdecode as we're not
doing anything with base paths any more.

Simplify requestUri detection

---

.travis.yml
composer.json

Fixes #58 
Updates the minimum version requirement to PHP >= 7.0.0.
Also fixes some of the broken unit tests in PHP 7.1 and higher. These were due to two problems:
1. The way the temp files were created to test uploaded files used tmpfile() which creates a resource, instead of a file name. fopen() no longer allows resources to be passed in. An alternative way to handle this would be to check for a resource and to use it directly, instead of calling fopen(), however we wouldn't be able to guarantee that the `w` flag was used. Opted to just fix how tests were written to use file names instead.
2. In URL creation empty checks were using falsy checks, which matched "0" as well. Updated to use exact `!== ''` checks instead.

Update minimum php version to 7.0.0

---

.travis.yml
composer.json
src/Cookies.php
src/Request.php
src/Stream.php
src/Uri.php

Added PHPStan for static code analysis. Fixed some of the errors PHPStan found which should be clear to change.
For checks higher than level 3 there are still some issues we need to discuss.
Tests are failing because of #44

Add PHPStan

---

README.md

Update README to include all of the decorated objects methods.

PSR-7 Decorators README

---

composer.json

`php-http/message-factory` mistakenly made its way into composer.json during the original PR but we are only using `psr/http-factory`.

Remove Unused Dependency php-http/message-factory

---

README.md
phpstan.neon.dist
src/Factory/DecoratedResponseFactory.php
src/Factory/DecoratedServerRequestFactory.php
src/Factory/DecoratedUriFactory.php
src/Response.php
src/ServerRequest.php
src/Uri.php
tests/ResponseTest.php
tests/ServerRequestTest.php
tests/TestCase.php
tests/UriTest.php

As per our Slack discussion. Removing the `Decorator` keyword and renaming decorated objects to match original Slim-Http namespacing.

Rename Decorators And Match Original Slim-Http Namespace

---

.travis.yml

Due to upcoming Linux infrastructure migration on Travis-CI we needed to remove `sudo: false` from our configuration.
This is a work in progress as I'm not entirely sure things will work. We shall see in a moment!

[WIP] Remove sudo usage from Travis-CI config

---

src/Response.php

Currently the withRedirect helper returns the response implementation object instead of a newly decorated response.

Decorate responses created by withRedirect helper

---

src/Response.php
src/ServerRequest.php
src/Uri.php

We would like to extend the response decorator in order to add additional domain-specific helpers. Unfortunately this is not possible at present as the current helpers do not make use of late static binding.
Using the response as an example, the current helpers take the basic format of:
```
/**
* @return Response
*/
public function withX(): ResponseInterface
{
$response = $this->response->withY();
return new Response($response, $this->streamFactory);
}
```
In order to allow extension it would be nice if these made use of late static binding to type hint and create the new decorated response as follows:
```
/**
* @return static
*/
public function withX(): ResponseInterface
{
$response = $this->response->withY();
return new static($response, $this->streamFactory);
}
```

Make use of late static binding to allow decorator extension

---

src/Response.php

This PR adds type hints and fixes docblocks for `\Slim\Http\Response`.

Add type hints and fix docblocks for \Slim\Http\Response

---

src/Response.php

Reverts some changes made in #84 
I missed it on the review but we can't return `self` because if those objects get extended it will throw an error.

Remove self return typehints from Response object

---

src/ServerRequest.php

This PR adds type hints and fixes docblocks for `\Slim\Http\ServerRequest`.

Add type hints and fix docblocks for \Slim\Http\ServerRequest

---

.travis.yml
README.md
composer.json
phpstan.neon.dist
src/Response.php
tests/Assets/plain.txt
tests/ResponseTest.php
tests/ServerRequestTest.php
tests/UriTest.php

Resuming to adopt the proposed direction in #88
**New Response Methods:**
- Response::withFile($file, $contentType)
- Response::withFileDownload($file, $name, $contentType)
**Behavior**
The `$file` parameter can be a `string` which points to a file, an existing `resource` handle or a `StreamInterface` as proposed by @roxblnfk
The `$name` parameter overrides the default `attachment` value for the `Content-Disposition` header. The given `$name` is filtered through `urlencode()` to ensure it is a valid header value.
The `$contentType` parameter accepts a `string` to override the `Content-Type` header to a user defined value. Defaults to `true` which attempts to detect the mime type via `mime_content_type()` and falls back to `application/octet-stream` otherwise. If set to `false` the …

[WIP] Response::withFile() and Response::withFileDownload()

---

tests/ServerRequestTest.php

Adds a test case for `\Slim\Http\ServerRequest::getParsedBody()` for unknown media type (i.e. no body parser) if in structured syntax suffix.

Add test case for unknown media type

---

tests/Assets/PhpFunctionOverrides.php
tests/ServerRequestTest.php
tests/bootstrap.php

This PR adds a test case to test it the method `\Slim\Http\ServerRequest::getMediaType()` would return `null` in case the php built-in function `preg_split()` fails.
In order to do that, I had to override the php built-in function.

Add test case for ServerRequest::getMediaType()

---

src/Factory/DecoratedResponseFactory.php
src/Factory/DecoratedServerRequestFactory.php
src/Factory/DecoratedUriFactory.php
src/Response.php
src/ServerRequest.php
src/Uri.php

Change properties that are private to be protected

---

src/ServerRequest.php

parse body if empty and has media type detected

---

src/Response.php
tests/ResponseTest.php

Instead of application/json; charset=utf-8, we should simply return application/json without the ; charset=utf-8 suffix.
More details: https://github.com/slimphp/Slim/issues/2629

Remove charset on json content-type

---

.gitignore
.travis.yml
composer.json
tests/Providers/LaminasDiactorosPsr17FactoryProvider.php
tests/Psr7Integration/Laminas/ResponseTest.php
tests/Psr7Integration/Laminas/ServerRequestTest.php
tests/Psr7Integration/Laminas/UriTest.php
tests/Psr7Integration/Nyholm/ResponseTest.php
tests/Psr7Integration/Nyholm/ServerRequestTest.php
tests/Psr7Integration/Nyholm/UriTest.php
tests/Psr7Integration/Zend/ResponseTest.php
tests/Psr7Integration/Zend/ServerRequestTest.php
tests/Psr7Integration/Zend/UriTest.php
tests/ResponseTest.php
tests/ServerRequestTest.php
tests/TestCase.php
tests/UriTest.php

This PR would set PHPUnit to version 8 and the minimal PHP version to 7.2. It would also add Laminas Diactoros as PSR7. Zend is left in there.

PHPUnit 8, PHP 7.2 and Laminas

---

composer.json

This PR updates the version for the php-autoload-override library.

Update php-autoload-override version

---

composer.json
phpstan.neon.dist
src/Factory/DecoratedServerRequestFactory.php
src/Response.php
src/ServerRequest.php
src/Uri.php

Closes #115
Note, the constructors of these objects are now final:
- ServerRequest
- Response
- URI
This is actually a BC change if they were extended. I have a feeling this is highly unlikely though.

Update phpstan to ^0.12.23

---

src/ServerRequest.php

The PHPDoc type of ServerRequest class getParam method's $default argument
is changed from "string" to "mixed", as dependent on request parameter its
default value can be expected to have another type(e.g. boolean). And if
there is a PHPStan or other analyser running in project an error is reported on
cases, where $default argument type is not string.  So as there is no obstacle for
doing this change, it is correct to change PHPDoc type of the argument.

Correct ServerRequest::getParam method PHPDoc

---

composer.json

This package does not provide the code of the psr/http-factory package (which defines interfaces). It provides psr/http-factory-implementation which is the virtual package to represent implementations of the interface.
Providing the wrong package while also requiring it creates issues with Composer 2, because the solver will consider that install psr/http-factory is not necessary as it is already provided.
Refs https://github.com/composer/composer/issues/9316
Closes #137

Fix the composer provide rule

---

composer.json
src/ServerRequest.php

This PR allows Slim to be installed in PHP 8 and passes all the tests and checks.
See also https://github.com/slimphp/Slim/pull/3015 and https://github.com/slimphp/Slim-Psr7/pull/169 for corresponding changes.
The same questions apply here:
* I implemented `disableXmlEntityLoader` as a `private static method`. Is this okay? I thought about making it `protected` or extracting it to a class, but I'm unsure about creating new "contracts".
* Coverage – conditional call to `libxml_disable_entity_loader`. Is it okay to just `@codeCoverageIgnore` some part that will only run in PHP 7 or PHP 8? How should situations like this be handled?
**Dependencies:** all dependencies have PHP 8-compatible releases now!

PHP 8 support

---

.github/workflows/tests.yml
README.md
composer.json
src/Factory/DecoratedResponseFactory.php
src/Factory/DecoratedServerRequestFactory.php
src/Factory/DecoratedUriFactory.php
src/Response.php
src/ServerRequest.php
src/Uri.php
tests/Psr7Integration/Laminas/UriTest.php

This PR;
- drops support for PHP 7.3,
- upgrades GitHub Actions dependencies,
- temporarily fixes the tests until [this issue](https://github.com/laminas/laminas-diactoros/issues/74) is resolved by disabling the `testPathWithMultipleSlashes` integration test for [`laminas-diactoros`](https://github.com/laminas/laminas-diactoros).

Drop support for PHP 7.3
